export const wordsList = {
  carro: [
    "Motor",
    "Roda",
    "Pneu",
    "Radiador",
    "Pistao",
    "Vela",
    "Biela",
    "Bloco-do-Motor",
    "Virabrequim",
    "Valvula-de-Admissao",
    "Mola",
    "Bomba-de-Combustivel",
    "Escapamento",
    "Parachoque",
    "Porta",
    "Volante",
    "Banco",
    "Bateria",
    "Amortecedor",
    "Caixa-de-Cambio",
    "Coletor",
    "Abafador",
    "Alternador",
    "Disco-de-Freio",
    "Pastilha-de-freio",
    "Correia",
    "Bomba-dagua",
    "Filtro-de-oleo",
    "Bucha-de-borracha",
  ],
  fruta: ["Banana", "Melancia", "Kiwi", "Mamão", "Pitaya"],
  computador: ["Mouse", "Teclado", "Monitor", "Processador", "Memoria"],
};
